application_port: 8000
database:
    host: "127.0.0.1"
    port: 5432
    username: "postgres"
    password: "password"
    database_name: "newsletter"
# These is an example. Using with mongo atlas port is not neccesary at this time.
